<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>TPE WEB 2</title>

    <link rel="stylesheet" href="<?= BASE_URL ?>public/css/style.css">
</head>

<body>

<header>

    <h1>TPE WEB 2</h1>

    <nav>

        <a href="<?= BASE_URL ?>home">Inicio</a>

        <a href="<?= BASE_URL ?>equipos">
            Equipos
        </a>

        <a href="<?= BASE_URL ?>jugadores">
            Jugadores
        </a>

        <a href="<?= BASE_URL ?>posiciones">
            Posiciones
        </a>

        <?php if ($user): ?>

            <a href="<?= BASE_URL ?>admin_jugadores">
                Admin jugadores
            </a>

            <a href="<?= BASE_URL ?>admin_equipos">
                Admin equipos
            </a>

            <a href="<?= BASE_URL ?>admin_posiciones">
                Admin posiciones
            </a>

            <a href="<?= BASE_URL ?>logout">
                Logout
                (<?= htmlspecialchars($user['username']) ?>)
            </a>

        <?php else: ?>

            <a href="<?= BASE_URL ?>login">
                Login
            </a>

        <?php endif; ?>

    </nav>

</header>

<main>